spring:
  application:
    name: ChatBot

  datasource:
    url: ${DB_URL}
    username: neondb_owner
    password: ${db_pass}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  ai:
    google:
      genai:
        api-key: ${api_key}
        chat:
          model:  gemini-3.6-flash

    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: always

logging:
  level:
    org:
      springframework:
        ai:
          chat:
            client:
              advisor:  DEBUG


server:
  port: ${PORT:8080}
